### ISSUE TITLE
can't see recipe in JEI on how to make items

### ISSUE THREAD

**Issue by Temil2006** [Jarva/All-The-Arcanist-Gear#4]
So, I'm a little confused. In JEI, I can't see how to craft the items from base parts. am I doing something wrong, or is there another mod or a config needed for it?

example of when i select one of the robes.

![image](https://github.com/user-attachments/assets/c4dfd96d-5d69-40d1-bcb2-47a3618a0ab5)

**Comment by Jarva** [comment]
Select the smithing table tab at the top, it uses the allthemodium smithing upgrades
