### ISSUE TITLE
Allthemodium spell book missing?

### ISSUE THREAD

**Issue by manavkulshrestha** [Jarva/All-The-Arcanist-Gear#6]
Hi, I wasn't sure where to put this but I don't see the allthemodium spell book from this mod in JEI. If it's relevant, I'm on ATM9. Does the version for 1.20.1 not have the spellbook?

**Comment by Jarva** [comment]
That's correct, the spellbooks are unfortunately 1.21 only as they rely on code added in newer versions

**Comment by manavkulshrestha** [comment]
Any possibility for adding backward compatibility? I'm playing ATM9 which is 1.20 only I think. ATM10 (1.21) is still under development and still doesn't have a lot of content.

**Comment by Jarva** [comment]
Unfortunately there's no possibility as Ars is not releasing features for 1.20.1 anymore.
